kind: Deployment
spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/fruits
              port: 8080
              scheme: HTTP
          env:
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
